source/protected/controllers/EmployeeController.php
<?php

class EmployeeController extends Controller {
    public function filters()
    {
        return array(
            'accessControl',
        );
    }

    public function accessRules()
    {
        return array(
            array(
                'allow',
                'actions' => array('index', 'edit', 'addmembers', 'addallmembers', 'removemember', 'removeallmembers'),
                'expression' => array($this, 'isAdmin'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex($id = null) {
        if (Yii::app()->user->isGuest) {
            $this->redirect('user/login');
        }

        $baseUrl = Yii::app()->baseUrl;
        $cs = Yii::app()->getClientScript();
        $cs->registerCssFile($baseUrl.'/css/listleavestyle.css');

        $model = null;
        if ($id != null) {
            $model = User::model()->findByPk($id);
        } else {
            $model = User::model()->findByPk(user()->id);
        }

        //sort
        $sort = 'user_role_id ASC';
        if (isset($_POST['sort'])) {
            $sort = $_POST['sort'];
        }

        // get user count
        $userCriteria = new CDbCriteria(array(
            'order' => $sort,
            'with' => 'userProfiles'
        ));
        $userCriteria->addCondition('user_status="Active"');
        $page = Yii::app()->request->getParam('page', 1);
//        $userCount = User::model()->count($userCriteria);

        // Pagination
//        $userPages = new CPagination($userCount);
        $pageSize = app()->getParams()['pageSize'];
        if (app()->request->isAjaxRequest) {
            if (app()->request->getParam('ajaxPageSize') != NULL) {
                $pageSize = app()->request->getParam('ajaxPageSize');
            }
        }
        $dataProvider = new CActiveDataProvider(
                'User',
                array(
                    'criteria' => $userCriteria,
                    'pagination' => array(
                        'pageSize' => $pageSize,
                    ),
                )
        );

//        echo "<pre>";
//        print_r(count($dataProvider->data));
//        echo "</pre>";
//        exit();

        $this->render('index', array(
            'dataProvider' => $dataProvider,
            'model' => $model,
            //'userPages' => $userPages,
            //'userCount' => $userCount,
            ));
    }

    //add Employee
    public function actionAddUser() {
        $userModel = new User;
        $userModel->setScenario('addEmployerUser');
        $this->performAjaxValidation($userModel);
        $listForRoleNameDropDown = CHtml::listData(UserRole::model()->findAll(), 'user_role_id', 'user_role_name');
        $listForUserStatusDropDown = CHtml::listData(User::model()->findAll(), 'user_status', 'user_status');

        if (isset($_POST['User'])) {
            $userModel->setAttributes($_POST['User']);
            $userModel->user_status = 'Active';

            if ($userModel->save()) {
                $userProfile = new UserProfile();
                $userProfile->setScenario('addEmployerUser');
                $userProfile->user_id = $userModel->user_id;
                $userProfile->user_dob = null;
                $userProfile->user_photo = 'avatar2.jpg';

                if ($userProfile->save()) {
                    Yii::app()->user->setFlash('success', 'New User has been added.');
                    $this->refresh();
                }
            }
        }

        $this->render('addUser', array(
            'userModel' => $userModel,
            'roleList' => $listForRoleNameDropDown,
            'statusList' => $listForUserStatusDropDown
        ));
    }

    protected function performAjaxValidation($userModel) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'addUser-form') {
            echo CActiveForm::validate($userModel);
            Yii::app()->end();
        }
    }

    public function actionEdit($id) {
        Yii::import('application.vendor.imageResize.*');
        require_once('ImageResize.php');

        //Yii::app()->theme='admin';
        $oldImage = '';

//        $user = User::model()->findByPk(Yii::app()->user->getId());
//        $userprofile = $user->profile;
        $userProfile = UserProfile::model()->with('user')->findByAttributes(array(
            'user_id' => $id,
        ));


        if ($userProfile->user_photo != 'photo.png') {
            $oldImage = $userProfile->user_photo;
        }

        $userProfile->setScenario('profileUpdate');

        if (isset($_POST['UserProfile'])) {
            $userProfile->attributes = $_POST['UserProfile'];
            $userProfile->user_gender = $_POST['UserProfile']['user_gender'];
            $userSignatureFile = CUploadedFile::getInstance($userProfile, 'uploadedFile');
            $userImageUploadFile = CUploadedFile::getInstance($userProfile, 'userImage');

            if (!empty($userSignatureFile)) {
                $basePath = dirname(Yii::app()->request->scriptFile) . '/uploads/';
                $rnd = md5('BDUOIU*&*(=-0_)' . rand(0, 999999) . 'TNKKOU**(');
                $fileName = "{$rnd}.{$userSignatureFile->extensionName}";

                if ($userSignatureFile->saveAs($basePath . $fileName)) {
                    $userProfile->user_signature_name = $userSignatureFile->name;
                    $userProfile->user_signature_type = $userSignatureFile->type;

                    $imageResize = new ImageResize();
                    $imageResize->setBasePath($basePath);
                    $imageResize->load($fileName);
                    $imageResize->resize(UserProfile::SIGNATURE_IMAGE_HEIGHT, UserProfile::SIGNATURE_IMAGE_WIDTH);
                    $imageResize->setBasePath($basePath);
                    $imageResize->save($fileName);
                    $userProfile->user_signature_size = $imageResize->getImageSizeInByte();
                    $userProfile->user_signature = base64_encode(file_get_contents($basePath . $fileName));
                    if (file_exists($basePath . $fileName))
                        unlink($basePath . $fileName);
                }

            }
            if (!empty($userImageUploadFile)) {
                $rnd = rand(0, 9999);
                $fileName = "{$userProfile->user->user_name}-{$rnd}.{$userImageUploadFile->extensionName}";  // random number + file name
                $userProfile->user_photo = $fileName;

                $basePath = dirname(Yii::app()->request->scriptFile) . '/images/user/';

                Yii::app()->user->setState('userImage', $userProfile->user_photo);
                $userImageUploadFile->saveAs($basePath . $userProfile->user_photo);
                if (!empty($oldImage)) {
                    if (file_exists($basePath . $oldImage))
                        unlink($basePath . $oldImage);
                }
                $imageResize = new ImageResize();
                $imageResize->setBasePath($basePath);
                $imageResize->load($userProfile->user_photo);
                $imageResize->resize(UserProfile::IMAGE_HEIGHT, UserProfile::IMAGE_WIDTH);
                $imageResize->setBasePath($basePath);
                $imageResize->save($userProfile->user_photo);
                $userProfile->save(false);
            }

            if ($userProfile->save()) {
                Yii::app()->user->setFlash('success', 'Your Profile has been updated.');
            }
        }
        $user = User::model()->findAllByAttributes(array(
            'user_role_id' => User::ROLE_GENERAL,
        ));

        $this->render('profile', array('model' => $userProfile));
    }

    public function actionRemoveMember()
    {
        if (app()->request->isAjaxRequest) {
            $leaderId = app()->request->getParam('leader_id');
            $memberId = app()->request->getParam('member_id');

            $model = LeaderMember::model()->findByAttributes(array('member_id' => $memberId));
            if ($model) {
                if ($model->delete()) {
                    LeaderMember::model()->deleteAllByAttributes(array('member_id' => $model->member_id));
                }
                $memberLeader = LeaderMember::model()->find('leader_id=:leader_id', array(':leader_id' => $leaderId));
                if ($memberLeader) {
                    echo 1;
                } else {
                    echo 2;
                }
            } else {
                echo 0;
            }
        }
    }

    public function actionRemoveAllMembers()
    {
        if (app()->request->isAjaxRequest) {
            $leader_id = app()->request->getParam('leader_id');
            $leaderMember = LeaderMember::model()->findAllByAttributes(array('leader_id' => $leader_id));
            $check = 1;

            foreach ($leaderMember as $item) {
                if ($item->delete()) {
                    LeaderMember::model()->deleteAllByAttributes(array('leader_id' => $item->leader_id));
                } else {
                    $check = 0;
                }
            }
            if ($check) {
                echo 1;
            } else {
                echo 0;
            }
        }
    }

    public function actionAddMembers()
    {
        if (app()->request->isAjaxRequest) {
            $leaderId = app()->request->getParam('leader_id');
            $freeMemberId = app()->request->getParam('free_member_id');
            $arrFreeMember = explode(',', $freeMemberId);
            $results = array();
            for ($i=0; $i<count($arrFreeMember); $i++) {
                $leaderMember = LeaderMember::model()->findByAttributes(array('member_id' => $arrFreeMember[$i]));
                if (is_null($leaderMember)) {
                    $model = new LeaderMember();
                    $model->leader_id = $leaderId;
                    $model->member_id = $arrFreeMember[$i];
                    $model->save();

source/protected/views/Employee/_viewEmployee.php
<?php
/* @var $data User */
/* @var $model EmployeeController */
//var_dump($data->userRole);die();
?>

<ul class="nav nav-tabs">
    <li class="<?php echo $data->user_id == $currentEmployeeId ? 'active' : ''; ?>" id="<?php echo $data->user_id; ?>">
        <a href="<?php echo Yii::app()->controller->createUrl("employee/index", array("id" => $data->user_id)); ?>" data-toggle="<?php echo $currentEmployeeId == $data->user_id ? 'tab' : ''; ?>">
            <span class="col-xs-1 t-center"><?php echo $data->user_id;?></span>
            <span class="col-xs-3"><img class="avatar-small" src="<?php echo '/images/user/' . CHtml::encode($data->userProfiles['user_photo']) ?>" alt=""></span>
            <span class="col-xs-4"><?php echo CHtml::encode($data->userProfiles['user_first_name']) . " " . CHtml::encode($data->userProfiles['user_last_name']); ?></span>
            <span class="col-xs-3"><?php echo $data->getRoleName(); ?></span>
        </a>
        <a href="<?php echo Yii::app()->controller->createUrl("employee/edit", array("id" => $data->user_id)); ?>">
            <span class="col-xs-1 glyphicon glyphicon-edit" style="padding-top: 12px;"></span>
        </a>
    </li>
</ul>

source/protected/views/Employee/addUser.php
<?php
/* @var $userModel EmployeeController */
/* @var $roleList EmployeeController */
/* @var $statusList EmployeeController */
$this->breadcrumbs = array(
    'Add User',
);
;?>
<head>
    <title>Add new User</title>
</head>
<?php
$form = $this->beginWidget('CActiveForm',
    array(
        'id' => 'addUser-form',
        'enableAjaxValidation' => true,
        'clientOptions' => array(
            'validateOnSubmit' => true
        ),
        'htmlOptions' => array(
            'class' => 'form-horizontal clearfix',
            'enctype' => 'multipart/form-data'
        )
    )
)
;?>

<?php if(Yii::app()->user->hasFlash('success')):;?>
    <div class="alert alert-success">
        <button data-dismiss="alert" class="close"></button>
        <?php echo Yii::app()->user->getFlash('success');?>
    </div>
<?php endif;?>

<section class="col-lg-12">
    <h1 class="title">Add new User</h1>

    <form class="form-horizontal col-lg-6" role="form">
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'user_status', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php
                    echo $form->dropDownList($userModel, 'user_status',
                        array('Active' => 'Active', 'Inactive' => 'Inactive'),
                        array(
                        'class' => 'form-control',
                        'style' => 'height: 35px; width: 280px',
                        'options' => array(
                            'Active' => array('selected' => true),
                            'Inactive' => array('selected' => false)
                            )
                    ))
                ;?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'user_role_id', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php echo $form->dropDownList($userModel, 'user_role_id', $roleList, array(
                        'class' => 'form-control',
                        'style' => 'height: 35px; width: 280px',
                        'options' => array(
                            '4' => array('selected' => true)
                        )
                    )
                );?>
            </div>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'user_name', array(
                'class' => 'col-lg-2 control-label'));?>
            <div class="col-lg-3">
                <?php echo $form->textField($userModel, 'user_name', array(
                    'class' => 'form-control',
                    'placeholder' => 'Enter Username',
                    'style' => 'height: 35px; width: 280px'
                ));?>
            </div>
            <?php echo $form->error($userModel, 'user_name');?>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'user_password', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php echo $form->passwordField($userModel, 'user_password', array(
                    'class' => 'form-control',
                    'style' => 'height: 35px; width: 280px',
                    'placeholder' => 'Enter Password'
                ));?>
            </div>
            <?php echo $form->error($userModel, 'user_password');?>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'verifyPassword', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php echo $form->passwordField($userModel, 'verifyPassword', array(
                    'class' => 'form-control',
                    'style' => 'height: 35px; width: 280px',
                    'placeholder' => 'Re-enter Password'
                ));?>
            </div>
            <?php echo $form->error($userModel, 'verifyPassword');?>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, 'user_email', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php echo $form->textField($userModel, 'user_email', array(
                    'class' => 'form-control',
                    'style' => 'height: 35px; width: 280px',
                    'placeholder' => 'Enter Email Address'
                ))
                ;?>
            </div>
            <?php echo $form->error($userModel, 'user_email')?>
        </div>
        <div class="form-group">
            <?php echo $form->labelEx($userModel, '', array(
                'class' => 'col-lg-2 control-label'
            ));?>
            <div class="col-lg-3">
                <?php echo CHtml::submitButton('Submit', array('class' => 'btn-success')) ;?>
                <?php echo CHtml::resetButton('Reset', array('class' => 'btn-default')) ;?>
            </div>
        </div>
    </form>
    <?php $this->endWidget();?>

</section>

<?php
/*
    echo $form->labelEx($model, 'user_first_name', array(
        'class' => 'col-lg-2 control-label'
    ));

    echo $form->textField($model, 'user_first_name', array(
        'class' => 'form-control',
        'placeholder' => 'First Name',
        'style' => 'height:35px; width:280px',
    ));

     echo $form->error($model, 'user_first_name');
*/
?>

source/protected/views/Employee/index.php
<?php
/* @var $this EmployeeController */
/* @var $data User */
/* @var $dataProvider EmployeeController */
/* @var $model User */
/* @var $user_id User */
/* @var $userPages EmployeeController */
/* @var $userCount EmployeeController*/

$this->breadcrumbs = array(
    'List Employees',
    //$model->user_id,
);
?>

<head>
    <title>List Employees</title>
</head>
<section class="col-lg-12">
<h1 class="title">List Employees</h1>

<div class="row clearfix">
<div class="col-lg-5">
    <div class="pull-left mail-view dropdown">
        <div>
            <a href="/employee/adduser"><button class="btn btn-success">New Employee</button></a>
        </div>
    <div class="clearfix"></div>
    <div>
    <?php
        echo CHtml::dropDownList('sort', '', array(
                'user_role_id ASC' => 'Position',
                'user_first_name ASC' => 'Name',
                ),
            array('id' => 'sortDrop',
                'options' => array(
                                    'user_role_id ASC' => array('disabled' => false, 'label' => 'position.ASC'),
                                    'user_first_name ASC' => array('label' => 'name.ASC')
                                  )
                )
        )
    ;?>

    </div>
    </div>


    <div class="clearfix"></div>
    <div id="list" class="top-20">
        <ul class="list-title">
            <li class="col-xs-1">No.</li>
            <li class="col-xs-3">Avatar</li>
            <li class="col-xs-4">Name</li>
            <li class="col-xs-3">Position</li>
            <li class="col-xs-1">Edit</li>
        </ul>
        <?php
        $this->widget('zii.widgets.CListView', array(
            'id' => 'userListView',
            'dataProvider' => $dataProvider,
            'summaryText' => '',
            'emptyText' => 'No data to display!',
            'itemView' => '_viewEmployee',
            'viewData' => array('currentEmployeeId' => $model->user_id),
            'htmlOptions' => array(
                'style' => 'text-align: center; color: #303030;',
            ),
            'itemsCssClass' => 'table table-hover table-striped table-bordered',
            'template' => '{items}<div class="config dropdown pull-right">
										<a class="tfoot-btn" data-toggle="dropdown" href="#">
										<span class="glyphicon glyphicon-cog"></span></a>
										<ul class="dropdown-menu">
											<li><a href="#">Show up to:</a></li>
											<li><a href="#" class="page_size" id="5">5 items</a></li>
											<li><a href="#" class="page_size" id="10">10 items</a></li>
											<li><a href="#" class="page_size" id="15">15 items</a></li>
											<li><a href="#" class="page_size" id="20">20 items</a></li>
										</ul>
									</div>{pager}{summary}',
            'pager' => array(
                'header' => '',//text before it
                'nextPageLabel'=>'<span class="glyphicon glyphicon-chevron-right"></span>',//overwrite nextPage lable
                'prevPageLabel'=>'<span class="glyphicon glyphicon-chevron-left"></span>',//overwrite prePage lable
                'internalPageCssClass' => 'hidden',
                'nextPageCssClass' => 'pager_next',
                'previousPageCssClass' => 'pager_prev'
            ),

            'pagerCssClass' => 'pull-right arrow tfoot-btn',
            'summaryText' =>'{start}-{end} Of {count}',
            'summaryCssClass' => 'pull-right summary',
        )); ?>
    </div>
</div>
<div class="tab-content col-lg-7">

<?php if($model != null) { ?>
<div class="tab-pane active" id="view">
    <h2><strong><?php echo $model->userProfiles['user_first_name']; ?></strong> Details </h2>

    <div class="row clearfix">
        <div class="col-lg-10 row">
            <div class="row-small">

                <span class="col-lg-4 field-name">First name:</span>
                <span class="col-lg-8"><?php echo $model->userProfiles['user_first_name']; ?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Last name:</span>
                <span class="col-lg-8"><?php echo $model->userProfiles['user_last_name']; ?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Gender:</span>
                <span class="col-lg-8"><?php echo $model->userProfiles['user_gender']; ?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Birthday:</span>
                <span class="col-lg-8"><?php echo date('d/m/Y', strtotime($model->userProfiles['user_birthday'])); ?></span>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="">
                <img class="avatar" alt="" src="<?php echo (!empty($model->userProfiles->user_photo) ? '/images/user/' . $model->userProfiles->user_photo : '/images/no_avatar.jpg'); ?>">
            </div>
        </div>

        <div class="col-lg-10 row">
            <div class="row-small">
                <span class="col-lg-4 field-name">Email:</span>
                <span class="col-lg-8"><?php echo $model->user_email; ?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Phone:</span>
                <span class="col-lg-8"><?php echo CHtml::encode($model->userProfiles['user_phone']);?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Address:</span>
                <span class="col-lg-8"><?php echo $model->userProfiles['user_address'];?></span>
            </div>
            <div class="row-small">
                <span class="col-lg-4 field-name">Position:</span>
                <span class="col-lg-8"><?php echo $model->getRoleName();?></span>
            </div>
        </div>
    </div>
    <div class="table-responsive clearfix top-20">
        <table class="table table-chart table-hover table-striped table-bordered">
            <?php
            if (!isset($_GET['id'])) {
                $this->widget('application.widgets.usersummary.UserSummary', array(
                    'userId' => user()->id,
                ));
            } else {
                $this->widget('application.widgets.usersummary.UserSummary', array(
                    'userId' => $_GET['id'],
                ));
            }
            ?>
        </table>
        <!--End responsive-->
    </div>
    <!--End table-responsive-->
</div>
<?php } ?>

</div>
</div>
</section>

<?php
Yii::app()->clientScript->registerScript('specialSort', '$("#sortDrop").on("change",
                    function(){
                                    $.fn.yiiListView.update("userListView",
                                                            {data:{sort:$(this).val()},
                                                            type:"POST"
                                                            })
                               }
                )
    '
);
?>

<script>
    $(document).on('click', '.page_size', function(){
        var pageSize = $(this).attr('id');
        $.fn.yiiListView.update('userListView', {
            url: $(this).attr('href'),
            data: {ajaxPageSize: pageSize}
        });
        return false;
    });
</script>