source/protected/controllers/LeaveController.php
<?php

class LeaveController extends Controller
{

    public $_leaveModel;
    public $modelClass = 'Leave';

    public function actionIndex()
    {
        if (Yii::app()->user->isGuest) {
            $this->redirect('/user/login');
        }

        if ($_POST) {
            $leave = $this->loadLeaveModel();
            if ($_POST['action'] == 'approve') {
                $leave->status = Leaves::STATUS_APPROVED;
            } elseif ($_POST['action'] == 'reject') {
                $leave->status = Leaves::STATUS_REJECTED;
            }

            $leave->notes = $_POST['message'];
            $leave->save();
        }

        // $leaveModel = $this->loadLeaveModel();

        /*
                $criteria = new CDbCriteria();
                $criteria->order = 'id ASC';
                $count = Leave::model()->count($criteria);
                $pages = new CPagination(Leave::model()->count());
                $pages->pageSize = 5;
                $pages->applyLimit($criteria);
                $leave = Leave::model()->findAll($criteria);
                $dataProvider = new CActiveDataProvider('leave');

                $this->render('index', array(
                    'leaveModel' => $leaveModel,
                    'dataProvider' => $dataProvider,
                    'pages' => $pages,
                    'leave' => $leave,

                ));*/
        $this->render('index', array(//  'leaveModel' => $leaveModel,
        ));
    }

    public function actionCreate()
    {
        if (Yii::app()->user->isGuest) {
            $this->redirect('/user/login');
        }


        $baseUrl = Yii::app()->baseUrl;
        $cs = Yii::app()->getClientScript();
        $cs->registerCssFile($baseUrl.'/css/listleavestyle.css');

        $model = new Leave('createleave');
        $modelSearch = new Leave('search');
        $modelSearch->unsetAttributes();

        if (isset($_GET['Leave'])) {
            $modelSearch->attributes = $_GET['Leave'];

        }
        $userProfile = UserProfile::model()->findByAttributes(array(
            'user_id' => Yii::app()->user->getId()
        ));
        $categoryLeave = Category::model()->findAll(array('select' => 'id, name', 'order' => 'name'));
        $approvingOfficer = User::model()->with(array(
            'userRole' => array(
                'select' => false,
                'joinType' => 'INNER JOIN',
                'condition' => 'userRole.user_role_id IN(1,2) AND userRole.user_status=1 AND t.user_status=1',
            ),
        ))->findAll();
        $urgentPhone = $userProfile->user_phone;


        // collect user input data
        if (isset($_POST['Leave'])) {
            $model->attributes = $_POST['Leave'];
            $model->requester_id = Yii::app()->user->id;
            $modelCate = Category::model()->findByAttributes(array('id' => $model->category_id));
            $fromTime = date_create($model->from_time);
            $toTime = date_create($model->to_time);
            $model->from_time = date_format($fromTime, 'Y-m-d H:i:s');
            $model->to_time = date_format($toTime, 'Y-m-d H:i:s');
            // count days exclude weekend(saturday & sunday)
            $model->applied_days = $this->countDay($fromTime, $toTime);

            $firstNameRequester = $userProfile->user_first_name;
            $lastNameRequester = $userProfile->user_last_name;
            $nameRequester = $firstNameRequester . ' ' . $lastNameRequester;

            $userProfileApprover = UserProfile::model()->findByAttributes(array('user_id' => $model->approver_id));
            $firstNameApprover = $userProfileApprover->user_first_name;
            $lastNameApprover = $userProfileApprover->user_last_name;
            $nameApprover = $firstNameApprover . ' ' . $lastNameApprover;

            $modelUser = User::model()->findByAttributes(array('user_id' => $model->approver_id));
            $emailApprover = $modelUser->user_email;
            $model->status = Leave::STATUS_PENDING;
            $model->created_at = date('Y-m-d H:i:s', time());
            $model->four_digit_year = CTimestamp::get4DigitYear(date('y', strtotime($model->from_time)));
            //validate user input and redirect to the previous page if valid
            if ($model->validate()) {
                if ($model->save()) {
                    $params = array(
                        'data' => array(
                            'requesterName' => $nameRequester,
                            'urgentPhone' => $model->urgent_phone,
                            'leaveType' => $modelCate->name,
                            'time' => $model->from_time,
                            'workingDaysApplied' => $model->applied_days,
                            'approvingOfficer' => $nameApprover,
                            'addressWhileOnLeave' => $model->wol_address,
                            'remark' => $model->reason,
                        ),
                        'to' => array($nameApprover, $emailApprover),
                        'cc' => $model->cc_email,

                    );

                    CeresMail::queue('leaveRecord', $params, EmailQueue::TYPE_URGENT);

                    Yii::app()->user->setFlash('createLeave', 'Your leave has been sent to system. We will respond to you as soon as possible.');
                    $this->refresh();
                }
            }
        }

        $criteria = new CDbCriteria();
        $count = Leave::model()->count($criteria);
        $pages = new CPagination($count);
//        $pages->pageSize = 4;
//        if (isset($_GET['pageSize']) && (int)$_GET['pageSize']) {
//            $pages->pageSize = $_GET['pageSize'];
//        }
        $pages->applyLimit($criteria);
        $leaves = Leave::model()->findAll($criteria);

        $this->render('createLeave', array(
            'userProfile' => $userProfile,
            'model' => $model,
            'modelSearch' => $modelSearch,
            //'filter' => $filter,
            'categoryLeave' => $categoryLeave,
            'approvingOfficer' => $approvingOfficer,
            'leaves' => $leaves,
            'pages' => $pages,
            'urgentPhone' => $urgentPhone,

        ));

    }

    public function actionGridView()
    {
        $model = new Leave('search');
        $modelLeave = new Leave();
        $model->unsetAttributes();

        if (isset($_GET['Leave'])) {
            $model->attributes = $_GET['Leave'];
        }
        if (!isset($_GET['ajax'])) {
            $this->render('_listLeaveRecord', array(
                'modelSearch' => $model,
                'modelLeave' => $modelLeave,
            ));
        } else {
            $this->renderPartial('_listLeaveRecord', array(
                'modelSearch' => $model
            ));
        }
    }

    protected function countDay($fromTime, $toTime)
    {
//        if (strtotime(date_format($fromTime, 'Y-m-d H:i:s')) >= strtotime(date_format($toTime, 'Y-m-d H:i:s'))) {
//            return $count = 0;
//        } else {
            $count = 1;
            while ($fromTime->diff($toTime)->days > 0) {
                $count += $fromTime->format('N') < 6 ? 1 : 0;
                $fromTime = $fromTime->add(new \DateInterval("P1D"));
            }
            return $count;
//        }
    }


    public function actionView()
    {
        $model = new Leave();
        if (isset($_POST['ajaxData'])) {
            $model = new Leave();
            $id = $_POST['ajaxData'];
            $modelLeave = $model->findByAttributes(array('id' => $id));

            $this->renderPartial('_viewLeave', array(
                'modelLeave' => $modelLeave
            ));
        }


    }

    public function accessRules()
    {
        return array(
            array('allow', // allow authenticated users to access all actions
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionApprove()
    {

        if (Yii::app()->request->isPostRequest) {
            $leave = $this->loadLeaveModel();
            $leave->approve();
            $this->redirect("/employee");
        }
    }

    public function actionReject()
    {
        if (Yii::app()->request->isPostRequest) {
            $leave = $this->loadLeaveModel();
            $leave->reject();
            $this->redirect('/employee');
        }
    }

    public function actionDelete()
    {

    }


    function loadLeaveModel()
    {
        if ($this->_leaveModel === null) {
            if (isset($_GET['id'])) {
                $this->_leaveModel = Leave::model()->findByPk($_GET['id']);
            }
            if ($this->_leaveModel === null) {
                throw new CHttpException(404, 'The requested page does not exist.');
            }
        }
        return $this->_leaveModel;
    }
    /*
    function loadModel($id)
    {
        $model = Leave::model()->findByPk($id);
        if($model === null) {
            throw new CHttpException(404, 'The requested page does not exist.');
        }
        return $model;

    }
    function getLeaveOption()
    {
        $leaveoption =  CHtml::listData(Leave::model()->findAll(),'category_id','id');
        return $leaveoption;
    }
*/

    // Uncomment the following methods and override them if needed
    /*
      public function filters()
      {
      // return the filter configuration for this controller, e.g.:
      return array(
      'inlineFilterName',
      array(
      'class'=>'path.to.FilterClass',
      'propertyName'=>'propertyValue',
      ),
      );
      }

      public function actions()
      {
      // return external action classes, e.g.:
      return array(
      'action1'=>'path.to.ActionClass',
      'action2'=>array(
      'class'=>'path.to.AnotherActionClass',
      'propertyName'=>'propertyValue',
      ),
      );
      }
     */
}

source/protected/views/layouts/login.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,600,400italic,600italic,700italic,700,800italic,800' rel='stylesheet' type='text/css'>
    <link href="<?php echo Yii::app()->request->baseUrl;?>/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl;?>/css/main.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl;?>/css/calendar.css" rel="stylesheet">
    <link href="<?php echo Yii::app()->request->baseUrl;?>/css/color.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/js/vendor/html5shiv.js"></script>
    <script src="<?php echo Yii::app()->request->baseUrl;?>/js/vendor/respond.min.js"></script>
    <![endif]-->
    <!--[if lte IE 7]><script src="<?php echo Yii::app()->request->baseUrl;?>/js/vendor/lte-ie7.js"></script><![endif]-->
</head>
<body id="login">
<div class="login">
    <h1 class="logo clearfix">
        <a href="/site/index"><img alt="" src="<?php echo Yii::app()->request->baseUrl;?>/img/logo.png"><span>CERES LMS</span></a>
    </h1>

    <?php
    $flashMessages = Yii::app()->user->getFlashes();
    if ($flashMessages) {
        echo '<ul class="flashes">';
        foreach($flashMessages as $key => $message) {
            echo '<li><div class="alert alert-' . $key . '" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <strong>' . $message . "</strong></div></li>\n";
        }
        echo '</ul>';
    }
    ?>

    <?php echo $content;?>
</div><!--End login-->

<!-- END COPYRIGHT -->
<script src="<?php echo Yii::app()->request->baseUrl;?>/js/vendor/bootstrap.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl;?>/js/vendor/bootstrap-datepicker.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl;?>/js/application.js"></script>
<script src="<?php echo Yii::app()->request->baseUrl;?>/js/main.js"></script>
</body>
</html>

source/protected/views/layouts/mail.php
<html>
<head>
	<meta content="text/html; charset=UTF-8" http-equiv="content-type">
</head>
<body>
<table cellspacing="0" cellpadding="10" style="color:#666;font:13px Arial;line-height:1.4em;width:100%;">
	<tbody>
		<tr>
            <td style="color:#4D90FE;font-size:25px;">
                <img src="http://www.wpsaeportal.com/themes/frontend/img/wps_logo.png"/>
            </td>
		</tr>
		<tr>
            <td style="color:#777;font-size:16px;padding-top:5px;">
            	<?php if(isset($data['description'])) echo $data['description'];  ?>
            </td>
		</tr>
		<tr>
            <td>
				<?php echo $content ?>
            </td>
		</tr>
	</tbody>
</table>
</body>
</html>

source/protected/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,300italic,600,400italic,600italic,700italic,700,800italic,800' rel='stylesheet' type='text/css'>
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/bootstrap.css" rel="stylesheet">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" rel="stylesheet">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/datepicker.css" rel="stylesheet">
        <link href="<?php echo Yii::app()->request->baseUrl; ?>/css/color.css" rel="stylesheet">
        <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/vendor/html5shiv.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>//js/vendor/respond.min.js"></script>
        <![endif]-->
        <!--[if lte IE 7]><script src="<?php echo Yii::app()->request->baseUrl; ?>/js/vendor/lte-ie7.js"></script><![endif]-->
    </head>
    <body id="index">
        <header id="header" class="navbar navbar-default navbar-fixed-top">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/site/index"><img src="<?php echo Yii::app()->request->baseUrl; ?>/img/logo-top.png" alt="">Ceres Leave Record</a>
            </div><!--home button-->

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>
                        <a class="circle" href="<?php echo url('/');?>">
                            <span class="glyphicon glyphicon-dashboard"></span>
                            <span class="text">Dashboard</span>
                        </a>
                    </li>
                    <li>
                        <a class="circle" href="/leave/create">
                            <span class="glyphicon glyphicon-plus"></span>
                            <span class="text">Add New Leave</span>
                        </a>
                    </li>
                    <?php if (isset(user()->role) && user()->role == User::ROLE_ADMIN) {?>
                        <li>
                            <a class="circle" href="/employee">
                                <span class="glyphicon glyphicon-list-alt"></span>
                                <span class="text">List Employees</span>
                            </a>
                        </li>
                    <?php }?>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="notification">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            <span class="glyphicon glyphicon-envelope"></span>
                            <?php
                                $leave = new Leave();
                                $leave->requester_id = user()->id;
                            ?>
                            <?php if ($leave->getPendingLeaveCount() > 0) : ?>
                                <span class="badge"><?php echo CHtml::encode($leave->getPendingLeaveCount()); ?></span>
                            <?php endif; ?>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <a href="<?php echo Yii::app()->controller->createUrl("/leave/index", array("id" => 1)); ?>">
                                    <div class="pull-left">
                                        <img class="avatar" alt="" src="/img/avatar2.jpg">
                                    </div>
                                    <div class="pull-right">
                                        <strong class="author">Mary Lee</strong>
                                        <span class="content">Lorem Ipsum is simply dummy text of the...</span>
                                        <em class="time">12/12/2013</em>
                                    </div>
                                </a>
                            </li>
                            <li>
                                <a href="<?php echo Yii::app()->controller->createUrl("/leave/index", array("id" => 2)); ?>">
                                    <div class="pull-left">
                                        <img class="avatar" alt="" src="img/avatar1.jpg">
                                    </div>
                                    <div class="pull-right">
                                        <strong class="author">Anna Lee</strong>
                                        <span class="content">Lorem Ipsum is simply dummy text of the...</span>
                                        <em class="time">12/12/2013</em>
                                    </div>
                                </a>
                            </li>
                            <li><a href="/site/index">Messages center</a></li>
                        </ul>
                    </li><!--notification-->
                    
                    <li class="account dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <img class="avatar" alt="" src="<?php echo Yii::app()->request->baseUrl; ?>/img/avatar-default.png">
                            <span>
                                <?php
                                $userProfile = UserProfile::model()->findByAttributes(array('user_id' => Yii::app()->user->id));
                                echo $userProfile->getAttribute('user_first_name') . " " . $userProfile->getAttribute('user_last_name')
                                ?>
                            </span>
                            <span class="glyphicon glyphicon-chevron-down"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="/user/userProfile/detail"><span class="glyphicon glyphicon-user"></span>My Profile</a></li>
                            <li><a href="/user/newPassword"><span class="glyphicon glyphicon-edit"></span>Change password</a></li>
                        </ul>
                    </li>
                    <li class="logout">
                        <a href="/user/logout" class="navbar-link"><span class="glyphicon glyphicon-log-out"></span>Logout</a>
                    </li>
                </ul>
            </div><!--navigator bar-->

        </header><!--header-->

        <div id="content" class="manage">
            <?php echo $content; ?>
        </div><!--main content-->

        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/vendor/bootstrap.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/vendor/bootstrap-datepicker.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/application.js"></script>
        <script src="<?php echo Yii::app()->request->baseUrl; ?>/js/main.js"></script>
    </body>
</html>